import json
import sys
import time
from collections import Counter
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from sklearn.metrics import accuracy_score, f1_score, precision_recall_fscore_support
from transformers import (
    LayoutLMv3ForSequenceClassification,
    LayoutLMv3Processor,
    Trainer,
    TrainingArguments,
)

# --- 0. Configuration ---
CONFIG = {
    "data_dir":           "./processed",
    "dataset_root":       "./processed",
    "output_dir":         "./models/layoutlmv3_run1",
    "model_name":         "microsoft/layoutlmv3-base",
    "epochs":             10,
    "batch_size":         8,
    "grad_accum":         1,
    "lr":                 5e-5,
    "warmup_ratio":       0.1,
    "weight_decay":       0.01,
    "max_length":         512,
    "seed":               42,
    "fp16":               True,
    "num_workers":        6,
    "eval_every_n_steps": 0,
}

# --- Helper classes ---
# // this part of code was generated by Claude 4.7 opus model //
# class to store the arguments
class Args:
    # initialize the arguments
    def __init__(self, d):
        # update the arguments
        self.__dict__.update(d)

# class to write to stdout and to a log file simultaneously
class Tee:
    # initialize the file and the stdout
    def __init__(self, path):
        # open the file
        self.file = open(path, "w", encoding="utf-8")
        # set the stdout
        self.stdout = sys.stdout

    # write the message to the file and the stdout
    def write(self, msg):
        # write the message to the stdout
        self.stdout.write(msg)
        # write the message to the file
        self.file.write(msg)
        # flush the file and the stdout
        self.file.flush()
        # flush the stdout
        self.stdout.flush()

    # flush the file and the stdout
    def flush(self):
        # flush the stdout
        self.stdout.flush()
        # flush the file
        self.file.flush()
# // end of code generated by Claude 4.7 opus model //


# // this part of code was modified by Claude 4.7 opus model //
class LayoutLMv3DocClassDataset(torch.utils.data.Dataset):
    # initialize the dataset
    def __init__(self, manifest, label2id, processor, dataset_root, max_length=512):
        # store the manifest list
        self.manifest = manifest
        # store the label-to-id mapping
        self.label2id = label2id
        # store the processor
        self.processor = processor
        # resolve and store the dataset root
        self.dataset_root = Path(dataset_root).resolve()
        # store the max sequence length
        self.max_length = max_length

    # return the number of examples
    def __len__(self):
        return len(self.manifest)

    # encode and return a single example by index
    def __getitem__(self, idx):
        # get the manifest entry
        m = self.manifest[idx]
        # get the image path
        img_path = Path(m["image_path"])
        # if the image path is relative, prepend the dataset root
        if not img_path.is_absolute():
            img_path = self.dataset_root / img_path
        # load the image and convert to RGB
        image = Image.open(img_path).convert("RGB")

        # encode the image, words, and boxes with the processor
        encoded = self.processor(
            image,
            text=m["words"],
            boxes=m["boxes"],
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt",
        )
        # squeeze the batch dimension off every tensor
        item = {k: v.squeeze(0) for k, v in encoded.items()}
        # add the label as a long tensor
        item["labels"] = torch.tensor(self.label2id[m["label"]], dtype=torch.long)
        # return the encoded example
        return item
# // end of code modified by Claude 4.7 opus model //

# helper function to compute classification metrics for the Trainer
def compute_metrics(eval_pred):
    # unpack the logits and labels
    logits, labels = eval_pred
    # take the argmax over classes to get predictions
    preds = np.argmax(logits, axis=-1)
    # compute macro precision, recall, and f1
    precision, recall, f1_macro, _ = precision_recall_fscore_support(
        labels, preds, average="macro", zero_division=0
    )
    # return the full metric dictionary
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_macro,
        "f1_weighted": f1_score(labels, preds, average="weighted", zero_division=0),
        "precision_macro": precision,
        "recall_macro": recall,
    }

# --- 1. Main script ---
# initialize the arguments
args = Args(CONFIG)
# build the output directory path
output_dir = Path(args.output_dir)
# create the output directory
output_dir.mkdir(parents=True, exist_ok=True)
# set the stdout to the log file
sys.stdout = Tee(output_dir / "run_log.txt")
# set the start time
t0 = time.time()

# print the header
print("=" * 70)
# print the header
print("LayoutLMv3 document classification training")
print("=" * 70)
# print the args
print(f"args: {vars(args)}")

# build the data directory path
data_dir = Path(args.data_dir)
# build the dataset root path
dataset_root = Path(args.dataset_root)

# --- 2. Load labels ---
# load the label map JSON
with (data_dir / "label_map.json").open("r", encoding="utf-8") as f:
    label_map = json.load(f)
# get the label-to-id mapping
label2id = label_map["label2id"]
# get the id-to-label mapping
id2label = {int(k): v for k, v in label_map["id2label"].items()}
# get the number of labels
num_labels = len(label2id)
# print the classes
print(f"\nClasses ({num_labels}): {list(label2id.keys())}")

# --- 3. Load manifests ---
# load the train manifest
train_manifest = load_manifest(data_dir / "train_manifest.jsonl")
# load the validation manifest
val_manifest = load_manifest(data_dir / "val_manifest.jsonl")
# print the number of train and validation samples
print(f"Train samples: {len(train_manifest)} | Val samples: {len(val_manifest)}")

# count the occurrences of each label in the train set
train_counts = Counter(m["label"] for m in train_manifest)
# print the train class distribution
print("\nTrain class distribution:")
# iterate over the sorted classes
for cls in sorted(train_counts):
    # print the class and its count
    print(f"  {cls:12s}  {train_counts[cls]:>6d}")

# --- 4. Processor and model ---
# load the processor 
processor = LayoutLMv3Processor.from_pretrained(args.model_name, apply_ocr=False)
# load the model
model = LayoutLMv3ForSequenceClassification.from_pretrained(
    args.model_name,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)

# build the lazy training dataset
train_ds = LayoutLMv3DocClassDataset(
    train_manifest, label2id, processor, dataset_root, args.max_length
)
# build the lazy validation dataset
val_ds = LayoutLMv3DocClassDataset(
    val_manifest, label2id, processor, dataset_root, args.max_length
)

# --- 5. Training ---
# build the eval/save strategy kwargs based on the config
if args.eval_every_n_steps > 0:
    eval_kwargs = {
        "eval_strategy": "steps",
        "eval_steps": args.eval_every_n_steps,
        "save_strategy": "steps",
        "save_steps": args.eval_every_n_steps,
    }
# otherwise evaluate by epoch
else:
    eval_kwargs = {
        "eval_strategy": "epoch",
        "save_strategy": "epoch",
    }

# build the training arguments
training_args = TrainingArguments(
    output_dir=str(output_dir),
    num_train_epochs=args.epochs,
    per_device_train_batch_size=args.batch_size,
    per_device_eval_batch_size=args.batch_size,
    gradient_accumulation_steps=args.grad_accum,
    learning_rate=args.lr,
    warmup_ratio=args.warmup_ratio,
    weight_decay=args.weight_decay,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
    logging_steps=50,
    fp16=args.fp16,
    seed=args.seed,
    dataloader_num_workers=args.num_workers,
    report_to="none",
    remove_unused_columns=False,
    **eval_kwargs,
)

# build the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics,
)

# start the timer
t_train = time.time()
# run the training loop
trainer.train()
# print the time taken to train
print(f"\nTraining finished in {(time.time() - t_train)/60:.1f} min")

# --- 6. Save best model and final metrics ---
# build the final model directory
final_dir = output_dir / "best"
# save the best model
trainer.save_model(str(final_dir))
# save the processor alongside the model
processor.save_pretrained(str(final_dir))

# evaluate on the validation set one more time
metrics = trainer.evaluate()
# print the final validation metrics
print("\nFinal validation metrics:", metrics)
# save the final metrics to a JSON file
with (output_dir / "final_metrics.json").open("w", encoding="utf-8") as f:
    json.dump(metrics, f, indent=2)

# --- 7. Summary ---
# create the summary dictionary
summary = {
    # number of train samples
    "n_train": len(train_manifest),
    # number of validation samples
    "n_val": len(val_manifest),
    # classes
    "classes": list(label2id.keys()),
    # final validation metrics
    "final_metrics": metrics,
    # total runtime in minutes
    "total_runtime_min": (time.time() - t0) / 60,
}

# save the summary
with (output_dir / "summary.json").open("w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2, default=str)

# print the total runtime
print("\n" + "=" * 70)
print(f"All done in {(time.time() - t0)/60:.1f} min")
print(f"Best model saved to: {final_dir.resolve()}")
print(f"Results saved to: {output_dir.resolve()}")
print("=" * 70)
