import json
import os
import sys
import time
from pathlib import Path

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import loguniform, randint
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import (
    RandomizedSearchCV,
    StratifiedKFold,
    cross_val_score,
    train_test_split,
)
from sklearn.pipeline import Pipeline

# --- 0. Configuration ---
CONFIG = {
    "data":            "./text_final.csv",  
    "out":             "./out",             
    "text_col":        "text",
    "label_col":       "class",
    "name_col":        "name",
    "val_size":        0.20,
    "n_iter":          200,   
    "cv":              5,      
    "n_jobs":          -1,
    "random_state":    42,
    "drop_classes":    "",    
    "min_class_count": 0,
}

# --- Helper classes ---
# // this part of code was generated by Claude 4.7 opus model //
# class to store the arguments
class Args:
    # initialize the arguments
    def __init__(self, d):
        # update the arguments
        self.__dict__.update(d)

# class to write to stdout and to a log file simultaneously
class Tee:
    # initialize the file and the stdout
    def __init__(self, path):
        # open the file
        self.file = open(path, "w", encoding="utf-8")
        # set the stdout
        self.stdout = sys.stdout

    # write the message to the file and the stdout
    def write(self, msg):
        # write the message to the stdout
        self.stdout.write(msg)
        # write the message to the file
        self.file.write(msg)
        # flush the file and the stdout
        self.file.flush()
        # flush the stdout
        self.stdout.flush()

    # flush the file and the stdout
    def flush(self):
        # flush the stdout
        self.stdout.flush()
        # flush the file
        self.file.flush()
# // end of code generated by Claude 4.7 opus model //

# --- Helper functions ---
# helper function to save the confusion matrix
def save_confusion_matrix(y_true, y_pred, classes, tag, out_dir):
    # calculate the confusion matrix
    cm = confusion_matrix(y_true, y_pred, labels=classes)
    # convert the confusion matrix to a pandas DataFrame
    cm_df = pd.DataFrame(cm, index=classes, columns=classes)
    # set the index name
    cm_df.index.name = "Skutečná třída"
    # set the columns name
    cm_df.columns.name = "Predikovaná třída"
    # save the confusion matrix to a CSV file
    cm_df.to_csv(out_dir / f"confusion_matrix_{tag}_param.csv")
    # create a figure and an axis

    # create a figure and an axis
    fig, ax = plt.subplots(figsize=(9, 7))
    # plot the confusion matrix
    ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes).plot(
        cmap=plt.cm.Blues, ax=ax, values_format="d"
    )
    # set the title
    ax.set_title(f"Confusion matrix")
    # save the figure
    plt.tight_layout()
    # save the figure
    plt.savefig(out_dir / f"confusion_matrix_{tag}_param.png", dpi=300, bbox_inches="tight")
    # close the figure

# helper function to save the train scores
def save_train_scores(model, X_train, y_train, X_val, y_val,
                      cv, n_jobs, random_state, tag, out_dir):
    # create a stratified k-fold object
    skf = StratifiedKFold(n_splits=cv, shuffle=True, random_state=random_state)

    # define the metrics
    metrics = ["accuracy", "f1_macro", "f1_weighted",
               "precision_weighted", "recall_weighted"]

    # create a list to store the scores
    rows = []
    # iterate over the metrics
    for m in metrics:
        # cross-validate the model
        scores = cross_val_score(model, X_train, y_train, cv=skf,
                                 scoring=m, n_jobs=n_jobs)
        # iterate over the scores
        for fold_idx, s in enumerate(scores):
            # add the score to the list
            rows.append({"metric": m, "fold": fold_idx, "score": s})
        # add the mean score to the list
        rows.append({"metric": m, "fold": "mean", "score": float(scores.mean())})
        # add the standard deviation score to the list
        rows.append({"metric": m, "fold": "std",  "score": float(scores.std())})

    # fit the model on the training data
    fitted = model.fit(X_train, y_train)
    # calculate the train accuracy
    train_acc = fitted.score(X_train, y_train)
    # calculate the validation accuracy
    val_acc = fitted.score(X_val, y_val)
    # add the train accuracy to the list
    rows.append({"metric": "train_accuracy_full", "fold": "-", "score": train_acc})
    # add the validation accuracy to the list
    rows.append({"metric": "val_accuracy_full",  "fold": "-", "score": val_acc})
    rows.append({"metric": "overfit_gap",         "fold": "-",
                 "score": train_acc - val_acc})

    # convert the list to a pandas DataFrame
    df = pd.DataFrame(rows)
    df.to_csv(out_dir / f"train_scores_{tag}_param.csv", index=False)
    # return the fitted model, the train accuracy, and the validation accuracy
    return fitted, train_acc, val_acc

# // this part of code was modified by Claude 4.7 opus model //
# helper function to save the feature importance    
def save_feature_importance(pipeline, out_dir, top_k=25):
    # try to get the feature names and the classifier
    try:
        # get the feature names
        feat_names = pipeline.named_steps["tfidf"].get_feature_names_out()
        # get the classifier
        clf = pipeline.named_steps["clf"]
    # if the feature names or the classifier are not found, return
    except (KeyError, AttributeError):
        return

    # create a list to store the feature importance
    rows = []
    # get the coefficients
    coef = clf.coef_
    # get the classes
    classes = clf.classes_

    # if the coefficients are for a binary classification, set the class list to the second class
    class_list = classes

    # iterate over the classes
    for i, cls in enumerate(class_list):
        # if the coefficients are for a binary classification, set the row index to 0
        row_idx = 0 if coef.shape[0] == 1 else i
        # get the coefficients for the current class
        c = coef[row_idx]
        # get the top k features
        top_pos = np.argsort(c)[-top_k:][::-1]
        # iterate over the top k features
        for rank, idx in enumerate(top_pos):
            # add the feature importance to the list
            rows.append({
                "class": cls, "rank": rank + 1,
                "feature": feat_names[idx], "coef": float(c[idx]),
            })
    # convert the list to a pandas DataFrame
    pd.DataFrame(rows).to_csv(out_dir / "feature_importance_best.csv", index=False)
# // end of code modified by Claude 4.7 opus model //

# --- 1. Main function ---¨
# initialize the arguments
args = Args(CONFIG)
# create the output directory
out_dir = Path(args.out)
# create the output directory
out_dir.mkdir(parents=True, exist_ok=True)
# set the stdout to the log file
sys.stdout = Tee(out_dir / "run_log.txt")
# set the start time
t0 = time.time()

# print the header
print("=" * 70)
# print the header
print("Text classification training")
print("=" * 70)
print(f"args: {vars(args)}")

# load the data
df = pd.read_csv(args.data)
# print the number of rows and the columns
print(f"\nLoaded {len(df)} rows from {args.data}")
# print the columns
print(f"Columns: {list(df.columns)}")

# drop rows missing label or text
before = len(df)
# drop rows missing label or text
df = df.dropna(subset=[args.label_col, args.text_col])
# drop rows with empty text or label
df = df[df[args.text_col].astype(str).str.strip() != ""]
# print the number of rows dropped
print(f"Dropped {before - len(df)} rows with missing/empty text or label")

# print the class distribution
print("\nClass distribution:")
# print the class distribution
print(df[args.label_col].value_counts().sort_index())

# get the text and label columns
X = df[args.text_col].astype(str)
# get the label column
y = df[args.label_col]

# split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=args.val_size,
    stratify=y,
    random_state=args.random_state,
)
# print the number of rows in the training and validation sets
print(f"\nSplit: train={len(X_train)}, val={len(X_val)}")
# get the unique classes
classes_sorted = sorted(y.unique())

# --- 2. Training with START parameters (baseline) ---
# print the header
print("\n" + "=" * 70)
print("1) Training with START parameters (baseline)")
print("=" * 70)

# create the start pipeline
start_pipeline = Pipeline([
    # create the tfidf vectorizer
    ("tfidf", TfidfVectorizer(
        max_features=20000,
        ngram_range=(1, 2),
    )),
    # create the logistic regression classifier
    ("clf", LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        random_state=args.random_state,
    )),
])

# start the timer
t_start = time.time()
# fit the start pipeline
fitted_start, tr_acc_s, val_acc_s = save_train_scores(
    start_pipeline, X_train, y_train, X_val, y_val,
    cv=args.cv, n_jobs=args.n_jobs, random_state=args.random_state,
    tag="start", out_dir=out_dir,
)
# print the time taken to fit the start pipeline
print(f"Start baseline fit in {time.time() - t_start:.1f}s")
print(f"  Train accuracy: {tr_acc_s:.4f}")
print(f"  Val   accuracy: {val_acc_s:.4f}")

# predict the start pipeline
y_pred_start = fitted_start.predict(X_val)
# create the classification report
report_start = classification_report(y_val, y_pred_start, digits=4)
# save the classification report
(out_dir / "classification_report_start_param.txt").write_text(
    report_start, encoding="utf-8"
)
print("\nClassification report (start):\n" + report_start)

# save confusion matrix
save_confusion_matrix(y_val, y_pred_start, classes_sorted,
                      tag="start", out_dir=out_dir)
# save the start pipeline
joblib.dump(fitted_start, out_dir / "model_start.pkl")

# --- 3. Hyperparameter search for BEST parameters ---
# print the header
print("\n" + "=" * 70)
print("2) Hyperparameter search for BEST parameters")
print("=" * 70)

# create the search pipeline
search_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression(
        random_state=args.random_state,
    )),
])

# create the parameter distribution
param_dist = {
    "tfidf__max_features": randint(2000, 80000),
    "tfidf__ngram_range": [(1, 1), (1, 2), (1, 3), (1, 4)],
    "tfidf__min_df": randint(1, 25),
    "tfidf__max_df": [0.85, 0.9, 0.95, 1.0],
    "tfidf__sublinear_tf": [True, False],
    "tfidf__analyzer": ["word", "char_wb"],
    "clf__C": loguniform(0.01, 50),
    "clf__max_iter": randint(500, 15000),
    "clf__class_weight": [None, "balanced"],
    "clf__solver": ["liblinear", "saga", "lbfgs"],
}

# create the stratified k-fold object
skf = StratifiedKFold(n_splits=args.cv, shuffle=True,
                      random_state=args.random_state)

# create the scoring dictionary
scoring = {
    "f1_macro":            "f1_macro",
    "f1_weighted":         "f1_weighted",
    "precision_weighted":  "precision_weighted",
    "recall_weighted":     "recall_weighted",
    "balanced_accuracy":   "balanced_accuracy",
}

# create the randomized search object
random_search = RandomizedSearchCV(
    search_pipeline,
    param_distributions=param_dist,
    n_iter=args.n_iter,
    cv=skf,
    scoring=scoring,
    refit="f1_macro",
    n_jobs=args.n_jobs,
    verbose=2,
    random_state=args.random_state,
    error_score=0.0, 
    return_train_score=False,
)

# start the timer
t_search = time.time()
# fit the randomized search object
random_search.fit(X_train, y_train)
# print the time taken to fit the randomized search object
print(f"\nSearch finished in {(time.time() - t_search)/60:.1f} min")
# print the best f1_macro score
print(f"Best CV f1_macro: {random_search.best_score_:.4f}")
# print the best parameters
print(f"Best params: {random_search.best_params_}")

# save the best parameters
with open(out_dir / "best_params.json", "w", encoding="utf-8") as f:
    json.dump(
        {k: (list(v) if isinstance(v, tuple) else v)
         for k, v in random_search.best_params_.items()},
        f, indent=2, default=str,
    )
# save the cv search results
pd.DataFrame(random_search.cv_results_).to_csv(
    out_dir / "cv_search_results.csv", index=False
)
# get the best model
best_model = random_search.best_estimator_

# fit the best model
fitted_best, tr_acc_b, val_acc_b = save_train_scores(
    best_model, X_train, y_train, X_val, y_val,
    cv=args.cv, n_jobs=args.n_jobs, random_state=args.random_state,
    tag="best", out_dir=out_dir,
)
# print the train and validation accuracy
print(f"\nBest model - train acc: {tr_acc_b:.4f}, val acc: {val_acc_b:.4f}")

# predict the best model
y_pred_best = fitted_best.predict(X_val)
# create the classification report
report_best = classification_report(y_val, y_pred_best, digits=4)
# save the classification report
(out_dir / "classification_report_best_param.txt").write_text(
    report_best, encoding="utf-8"
)
print("\nClassification report (best):\n" + report_best)

# save confusion matrix
save_confusion_matrix(y_val, y_pred_best, classes_sorted,
                      tag="best", out_dir=out_dir)
# save the feature importance
save_feature_importance(fitted_best, out_dir)
# save the best model
joblib.dump(
    {"model": fitted_best, "classes": list(fitted_best.classes_),
     "best_params": random_search.best_params_},
    out_dir / "model_best.pkl",
)

# --- 4. Summary ---
# create the summary dictionary
summary = {
    # print the number of rows
    "n_rows": int(len(df)),
    # print the number of rows in the training set
    "n_train": int(len(X_train)),
    # print the number of rows in the validation set
    "n_val": int(len(X_val)),
    # print the classes
    "classes": [str(c) for c in classes_sorted],
    # print the train and validation accuracy
    "start": {"train_acc": tr_acc_s, "val_acc": val_acc_s},
    # print the best f1_macro score
    "best":  {"train_acc": tr_acc_b, "val_acc": val_acc_b,
              "cv_f1_macro": float(random_search.best_score_)},
    # print the total runtime in minutes
    "total_runtime_min": (time.time() - t0) / 60,
}

# save the summary
with open(out_dir / "summary.json", "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2)

# print the total runtime in minutes
print("\n" + "=" * 70)
print(f"All done in {(time.time() - t0)/60:.1f} min")
print(f"Results saved to: {out_dir.resolve()}")
print("=" * 70)