import json
import os
import shutil
import sys
import time
from copy import copy as _copy
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import albumentations as A
import numpy as np
import torch
from PIL import Image
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
from torch.utils.data import Dataset
from transformers import (
    AutoImageProcessor,
    RTDetrV2ForObjectDetection,
    Trainer,
    TrainerCallback,
    TrainingArguments,
)

# --- 0. Configuration ---
CONFIG = {
    "data_dir":        "./data",
    "output_dir":      "./out",
    "model_name":      "ds4sd/docling-layout-heron-101",
    "image_size":      640,
    "epochs":          40,
    "patience":        8,
    "batch_size":      4,
    "grad_accum":      4,
    "lr":              5e-5,
    "backbone_lr":     5e-6,
    "weight_decay":    1e-4,
    "warmup_steps":    200,
    "eval_every":      1,
    "freeze_backbone": False,
    "seed":            42,
}

# class-id
ID2LABEL = {
    0: "mapove_pole",
    1: "vykaz",
    2: "BPEJ",
    3: "ss",
    4: "popis",
    5: "klad",
}
LABEL2ID = {v: k for k, v in ID2LABEL.items()}

# --- Helper classes ---
# // this part of code was generated by Claude 4.7 opus model //
# class to store the arguments
class Args:
    # initialize the arguments
    def __init__(self, d):
        # update the arguments
        self.__dict__.update(d)

# class to write to stdout and to a log file simultaneously
class Tee:
    # initialize the file and the stdout
    def __init__(self, path):
        # open the file
        self.file = open(path, "w", encoding="utf-8")
        # set the stdout
        self.stdout = sys.stdout

    # write the message to the file and the stdout
    def write(self, msg):
        # write the message to the stdout
        self.stdout.write(msg)
        # write the message to the file
        self.file.write(msg)
        # flush the file and the stdout
        self.file.flush()
        # flush the stdout
        self.stdout.flush()

    # flush the file and the stdout
    def flush(self):
        # flush the stdout
        self.stdout.flush()
        # flush the file
        self.file.flush()
# // end of code generated by Claude 4.7 opus model //

# --- Helper functions and classes ---
# COCO-format detection dataset; emits dicts in the shape RT-DETR's image processor expects
# // this part of code was modified by Claude 4.7 opus model //
class CocoDetectionDataset(Dataset):
    # initialize the dataset
    def __init__(self, ann_file, img_dir, transform):
        # load the COCO annotations
        self.coco = COCO(str(ann_file))
        # store the image directory
        self.img_dir = Path(img_dir)
        # store the augmentation pipeline
        self.transform = transform
        # store the sorted image ids for deterministic ordering
        self.ids = sorted(self.coco.imgs.keys())

    # return the number of images
    def __len__(self):
        return len(self.ids)

    # load and augment a single example
    def __getitem__(self, idx):
        # get the image id
        img_id = self.ids[idx]
        # get the image info dict
        info = self.coco.imgs[img_id]
        # build the image path
        img_path = self.img_dir / info["file_name"]
        # load the image as a numpy array
        image = np.array(Image.open(img_path).convert("RGB"))

        # get the annotation ids for this image
        ann_ids = self.coco.getAnnIds(imgIds=img_id)
        # load the annotations
        anns = self.coco.loadAnns(ann_ids)

        # extract the bboxes (COCO [x, y, w, h])
        bboxes = [a["bbox"] for a in anns]
        # extract the category ids
        labels = [a["category_id"] for a in anns]

        # apply the augmentation pipeline if provided
        if self.transform is not None:
            out = self.transform(image=image, bboxes=bboxes, category=labels)
            image = out["image"]
            bboxes = out["bboxes"]
            labels = out["category"]

        # rebuild COCO-style annotations for the image processor
        formatted = []
        # iterate over the bboxes and labels
        for bbox, cat in zip(bboxes, labels):
            # unpack the bbox
            x, y, w, h = bbox
            # append the formatted annotation
            formatted.append({
                "image_id": img_id,
                "category_id": int(cat),
                "bbox": [float(x), float(y), float(w), float(h)],
                "area": float(w * h),
                "iscrowd": 0,
            })

        # return the dict expected by the image processor
        return {
            "image_id": img_id,
            "image": image,
            "annotations": formatted,
        }

# helper function to build the augmentation pipeline (separate train/val branches)
def build_transforms(image_size, train):
    # training: moderate geometric + color aug, bbox handling done by albumentations in COCO format
    if train:
        return A.Compose(
            [
                A.LongestMaxSize(max_size=image_size),
                A.PadIfNeeded(
                    min_height=image_size,
                    min_width=image_size,
                    border_mode=0,  # constant black
                ),
                A.HorizontalFlip(p=0.5),
                A.RandomBrightnessContrast(p=0.3),
                A.HueSaturationValue(
                    hue_shift_limit=5, sat_shift_limit=10, val_shift_limit=10, p=0.3
                ),
                A.GaussNoise(p=0.2),
            ],
            bbox_params=A.BboxParams(
                format="coco",
                label_fields=["category"],
                min_area=4,           # tiny floor; we don't want to drop small BPEJ/ss boxes
                min_visibility=0.3,   # drop boxes that get mostly cropped (>70% lost)
            ),
        )
    # validation: just LongestMaxSize + PadIfNeeded to preserve aspect ratio
    else:
        return A.Compose(
            [
                A.LongestMaxSize(max_size=image_size),
                A.PadIfNeeded(
                    min_height=image_size, min_width=image_size, border_mode=0
                ),
            ],
            bbox_params=A.BboxParams(format="coco", label_fields=["category"]),
        )

# collator: converts a batch of Dataset items to model inputs via the image processor
@dataclass
class DetrCollator:
    # the image processor
    image_processor: Any

    # collate a batch
    def __call__(self, batch):
        # extract images
        images = [ex["image"] for ex in batch]
        # extract annotations
        annotations = [
            {"image_id": ex["image_id"], "annotations": ex["annotations"]}
            for ex in batch
        ]
        # encode with the processor
        encoded = self.image_processor(
            images=images,
            annotations=annotations,
            return_tensors="pt",
        )
        # return the encoded batch
        return encoded

# stateful COCO mAP evaluator; accumulates predictions across the eval run
class CocoMapEvaluator:
    # initialize the evaluator
    def __init__(self, coco_gt, id2label):
        # store the ground-truth COCO object
        self.coco_gt = coco_gt
        # store the id-to-label mapping
        self.id2label = id2label
        # reset the results list
        self.reset()

    # reset the accumulated predictions
    def reset(self):
        self.results = []

    # add a batch of predictions
    def update(self, image_ids, predictions):
        # iterate over each image's predictions
        for img_id, pred in zip(image_ids, predictions):
            # extract boxes (xyxy in original image coords)
            boxes = pred["boxes"].tolist()
            # extract scores
            scores = pred["scores"].tolist()
            # extract labels
            labels = pred["labels"].tolist()
            # convert each prediction to COCO result format
            for (x1, y1, x2, y2), s, l in zip(boxes, scores, labels):
                self.results.append({
                    "image_id": int(img_id),
                    "category_id": int(l),
                    "bbox": [x1, y1, x2 - x1, y2 - y1],
                    "score": float(s),
                })

    # compute the COCO mAP metrics
    def summarize(self):
        # if no predictions, return zeros
        if not self.results:
            return {"map": 0.0, "map_50": 0.0, "map_75": 0.0}
        # load predictions into the COCO API
        coco_dt = self.coco_gt.loadRes(self.results)
        # build the COCO evaluator
        coco_eval = COCOeval(self.coco_gt, coco_dt, "bbox")
        # run evaluate, accumulate, summarize
        coco_eval.evaluate()
        coco_eval.accumulate()
        coco_eval.summarize()
        # extract the 12-element COCO stats array
        stats = coco_eval.stats
        # return the named subset we care about
        return {
            "map":     float(stats[0]),  # AP @ IoU=0.50:0.95
            "map_50":  float(stats[1]),
            "map_75":  float(stats[2]),
            "map_s":   float(stats[3]),
            "map_m":   float(stats[4]),
            "map_l":   float(stats[5]),
            "mar_100": float(stats[8]),
        }

# manual eval loop - computes COCO mAP on a dataset
@torch.no_grad()
def evaluate_model(model, image_processor, dataset, batch_size, device,
                   threshold=0.0, return_predictions=False):
    # set the model to eval mode
    model.eval()
    # build the COCO mAP evaluator
    evaluator = CocoMapEvaluator(dataset.coco, ID2LABEL)
    # optionally collect per-image predictions
    predictions_by_img = {} if return_predictions else None

    # iterate over the val image ids in deterministic order
    img_ids_all = sorted(dataset.coco.imgs.keys())
    # batch the eval loop
    for start in range(0, len(img_ids_all), batch_size):
        # get the batch of image ids
        batch_ids = img_ids_all[start:start + batch_size]
        # collect images and original sizes
        images = []
        sizes = []
        # iterate over the batch
        for img_id in batch_ids:
            # get the image info
            info = dataset.coco.imgs[img_id]
            # load the original image
            img = Image.open(dataset.img_dir / info["file_name"]).convert("RGB")
            # store the image
            images.append(img)
            # store the original (H, W)
            sizes.append((info["height"], info["width"]))

        # build the target_sizes tensor on the same device as the model
        target_sizes = torch.tensor(sizes, device=device)

        # encode the batch with the image processor
        encoded = image_processor(images=images, return_tensors="pt")
        # move the encoded batch to the device
        encoded = {k: v.to(device) for k, v in encoded.items()}
        # run the model forward pass
        outputs = model(**encoded)
        # post-process to original image coords
        results = image_processor.post_process_object_detection(
            outputs, target_sizes=target_sizes, threshold=threshold
        )
        # accumulate into the COCO evaluator
        evaluator.update(batch_ids, results)

        # optionally collect predictions for downstream use
        if return_predictions:
            for img_id, r in zip(batch_ids, results):
                boxes = r["boxes"].tolist()
                scores = r["scores"].tolist()
                labels = r["labels"].tolist()
                predictions_by_img[int(img_id)] = [
                    {
                        "bbox": [x1, y1, x2 - x1, y2 - y1],  # xywh
                        "score": float(s),
                        "label": int(l),
                    }
                    for (x1, y1, x2, y2), s, l in zip(boxes, scores, labels)
                ]

    # compute the final metrics
    metrics = evaluator.summarize()
    # restore train mode
    model.train()
    # return metrics, optionally with predictions
    if return_predictions:
        return metrics, predictions_by_img
    return metrics
# // end of code modyfied by Claude 4.7 opus model //

# --- 1. Main script ---
# initialize the arguments
args = Args(CONFIG)
# build the data directory path
data_dir = Path(args.data_dir)
# build the output directory path
output_dir = Path(args.output_dir)
# create the output directory
output_dir.mkdir(parents=True, exist_ok=True)
# set the stdout to the log file
sys.stdout = Tee(output_dir / "run_log.txt")
# set the start time
t0 = time.time()

# print the header
print("=" * 70)
# print the header
print("RT-DETRv2 (docling-layout-heron-101) detection training")
print("=" * 70)
# print the args
print(f"args: {vars(args)}")

# set the random seeds
torch.manual_seed(args.seed)
np.random.seed(args.seed)

# save the training args alongside the run log
with open(output_dir / "training_args.json", "w", encoding="utf-8") as f:
    json.dump({k: str(v) for k, v in vars(args).items()}, f, indent=2)

# --- 2. Load model and processor ---
# print the loading message
print(f"\nLoading {args.model_name} ...")
# load the image processor
image_processor = AutoImageProcessor.from_pretrained(args.model_name)

# load the model
model = RTDetrV2ForObjectDetection.from_pretrained(
    args.model_name,
    num_labels=len(ID2LABEL),
    id2label=ID2LABEL,
    label2id=LABEL2ID,
    ignore_mismatched_sizes=True,
    anchor_image_size=(args.image_size, args.image_size),
)

# optionally freeze the backbone for tiny datasets
if args.freeze_backbone:
    # print the freeze message
    print("Freezing backbone parameters...")
    # iterate over the model parameters
    for name, p in model.named_parameters():
        # freeze any parameter whose name contains 'backbone'
        if "backbone" in name:
            p.requires_grad = False

# --- 3. Datasets ---
# build the training dataset
train_ds = CocoDetectionDataset(
    data_dir / "annotations" / "train.json",
    data_dir / "images" / "train",
    transform=build_transforms(args.image_size, train=True),
)
# build the validation dataset
val_ds = CocoDetectionDataset(
    data_dir / "annotations" / "val.json",
    data_dir / "images" / "val",
    transform=build_transforms(args.image_size, train=False),
)
# print the dataset sizes
print(f"Train: {len(train_ds)} images   Val: {len(val_ds)} images")

# --- 4. Parameter groups: lower LR for backbone ---
# split the trainable parameters into backbone and other groups
backbone_params, other_params = [], []
# iterate over the named parameters
for name, p in model.named_parameters():
    # skip frozen parameters
    if not p.requires_grad:
        continue
    # route to the right group based on the name
    (backbone_params if "backbone" in name else other_params).append(p)
# build the optimizer parameter groups
optimizer_grouped = [
    {"params": backbone_params, "lr": args.backbone_lr},
    {"params": other_params, "lr": args.lr},
]

# --- 5. Training arguments ---
# build the training arguments
training_args = TrainingArguments(
    output_dir=str(output_dir),
    num_train_epochs=args.epochs,
    per_device_train_batch_size=args.batch_size,
    gradient_accumulation_steps=args.grad_accum,
    learning_rate=args.lr,
    weight_decay=args.weight_decay,
    warmup_steps=args.warmup_steps,
    max_grad_norm=1.0,                
    logging_dir=str(output_dir / "logs"),
    logging_steps=20,
    save_strategy="epoch",
    save_total_limit=3,
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),
    dataloader_num_workers=4,
    remove_unused_columns=False,
    report_to=["tensorboard"],
    seed=args.seed,
)

# build the custom optimizer with per-group LRs
optimizer = torch.optim.AdamW(optimizer_grouped, weight_decay=args.weight_decay)

# build the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    data_collator=DetrCollator(image_processor=image_processor),
    optimizers=(optimizer, None),  # scheduler built by Trainer
)

# --- 6. Evaluation callback ---
# wipe any stale final/ from a previous run in this same output_dir
stale_final = output_dir / "final"
if stale_final.exists():
    print(f"Removing stale {stale_final} from previous run.")
    shutil.rmtree(stale_final)

# track the best mAP so far across the run
best_map = {"value": -1.0, "epoch": -1, "evals_since_best": 0}
# get the device the model lives on
device = next(model.parameters()).device

# // this part of code was modifies by Claude 4.7 opus model //
# helper function to atomically save the best model
def _atomic_save_best(metrics, epoch):
    # build the final and tmp directories
    final_dir = output_dir / "final"
    tmp_dir = output_dir / "final.tmp"
    # remove any leftover tmp dir
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    # create the tmp dir
    tmp_dir.mkdir(parents=True)

    # save the model and processor to the tmp dir
    model.save_pretrained(tmp_dir)
    image_processor.save_pretrained(tmp_dir)
    # save the eval metrics
    with open(tmp_dir / "eval_metrics.json", "w", encoding="utf-8") as f:
        json.dump(metrics | {"epoch": epoch}, f, indent=2)

    # atomically swap the tmp dir into place
    if final_dir.exists():
        shutil.rmtree(final_dir)
    os.rename(tmp_dir, final_dir)
    # return the final path
    return final_dir

# Trainer callback that runs COCO eval at the end of every Nth epoch
class EvalCallback(TrainerCallback):
    # called by the Trainer at the end of each epoch
    def on_epoch_end(self, cbargs, state, control, **kwargs):
        # get the integer epoch
        epoch = int(state.epoch or 0)
        # skip if this isn't an eval epoch
        if epoch == 0 or epoch % args.eval_every != 0:
            return
        # run the manual eval
        print(f"\n[eval] Running COCO eval on val set at epoch {epoch} ...")
        metrics = evaluate_model(
            model, image_processor, val_ds,
            batch_size=args.batch_size, device=device,
            return_predictions=False,
        )
        print(f"[eval] {metrics}")
        # log to Trainer state so it shows up in logs
        if state.log_history is not None:
            state.log_history.append(
                {f"eval/{k}": v for k, v in metrics.items()} | {"epoch": epoch}
            )

        # save best model atomically if this beats the running best mAP
        if metrics["map"] > best_map["value"]:
            best_map["value"] = metrics["map"]
            best_map["epoch"] = epoch
            best_map["evals_since_best"] = 0
            best_dir = _atomic_save_best(metrics, epoch)
            print(f"[eval] New best mAP={metrics['map']:.4f} saved to {best_dir}")
        # otherwise bump the patience counter and possibly early-stop
        else:
            best_map["evals_since_best"] += 1
            print(f"[eval] No improvement ({best_map['evals_since_best']}/{args.patience} evals "
                  f"since best mAP={best_map['value']:.4f} at epoch {best_map['epoch']})")
            if best_map["evals_since_best"] >= args.patience:
                print(f"[eval] EARLY STOPPING: val mAP plateaued for {args.patience} evals")
                control.should_training_stop = True

# attach the eval callback to the Trainer
trainer.add_callback(EvalCallback())
# // end of code modified by Claude 4.7 opus model //

# --- 8. Train ---
# start the timer
t_train = time.time()
# run the training loop
print("\nStarting training...")
trainer.train()
# print the time taken to train
print(f"\nTraining finished in {(time.time() - t_train)/60:.1f} min")

# --- 9. Summary ---
# create the summary dictionary
summary = {
    # number of train images
    "n_train": len(train_ds),
    # number of validation images
    "n_val": len(val_ds),
    # classes
    "classes": list(ID2LABEL.values()),
    # best mAP info
    "best_map": best_map["value"],
    "best_epoch": best_map["epoch"],
    # total runtime in minutes
    "total_runtime_min": (time.time() - t0) / 60,
}

# save the summary
with open(output_dir / "summary.json", "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2, default=str)

# print the final messages
print("\n" + "=" * 70)
print(f"All done in {(time.time() - t0)/60:.1f} min")
print(f"Best val mAP={best_map['value']:.4f} at epoch {best_map['epoch']}")
print(f"Best model saved to: {(output_dir / 'final').resolve()}")
print(f"Latest Trainer checkpoints in: {output_dir.resolve()} (checkpoint-*)")
print(f"Results saved to: {output_dir.resolve()}")
print("=" * 70)
