import ast
import json
import os
import sys
import time
import warnings
from pathlib import Path

from sklearn.exceptions import ConvergenceWarning, UndefinedMetricWarning
warnings.filterwarnings("ignore", category=UndefinedMetricWarning)
warnings.filterwarnings("ignore", category=ConvergenceWarning)
os.environ.setdefault("PYTHONWARNINGS",
                      "ignore::sklearn.exceptions.ConvergenceWarning,"
                      "ignore::sklearn.exceptions.UndefinedMetricWarning")

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import loguniform, randint
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import (
    RandomizedSearchCV,
    StratifiedKFold,
    cross_val_score,
    train_test_split,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# --- 0. Configuration ---
CONFIG = {
    "data":            "./text_final.csv",
    "out":             "./out",
    "text_col":        "text",
    "label_col":       "class",
    "name_col":        "name",
    "embedding_col":   "image_embedding",
    "val_size":        0.20,
    "n_iter":          200,
    "cv":              5,
    "n_jobs":          -1,
    "random_state":    42,
    "drop_classes":    "",
    "min_class_count": 0,
}

# --- Helper classes ---
# // this part of code was generated by Claude 4.7 opus model //
# class to store the arguments
class Args:
    # initialize the arguments
    def __init__(self, d):
        # update the arguments
        self.__dict__.update(d)

# class to write to stdout and to a log file simultaneously
class Tee:
    # initialize the file and the stdout
    def __init__(self, path):
        # open the file
        self.file = open(path, "w", encoding="utf-8")
        # set the stdout
        self.stdout = sys.stdout

    # write the message to the file and the stdout
    def write(self, msg):
        # write the message to the stdout
        self.stdout.write(msg)
        # write the message to the file
        self.file.write(msg)
        # flush the file and the stdout
        self.file.flush()
        # flush the stdout
        self.stdout.flush()

    # flush the file and the stdout
    def flush(self):
        # flush the stdout
        self.stdout.flush()
        # flush the file
        self.file.flush()
# // end of code generated by Claude 4.7 opus model //

# --- Helper functions ---
# // this part of code was modified by Claude 4.7 opus model //
# helper function to parse a single embedding cell into a list of floats
def parse_embedding(val):
    # if the value is None, return None
    if val is None:
        return None
    # if the value is already a list/tuple/ndarray, try to cast to floats
    if isinstance(val, (list, tuple, np.ndarray)):
        try:
            return [float(x) for x in val]
        except (TypeError, ValueError):
            return None
    # if the value is not a string, give up
    if not isinstance(val, str):
        return None
    # strip the string
    s = val.strip()
    # if the string is empty, return None
    if not s:
        return None
    # try JSON first (fastest), then literal_eval as fallback
    try:
        parsed = json.loads(s)
    except (json.JSONDecodeError, ValueError):
        try:
            parsed = ast.literal_eval(s)
        except (ValueError, SyntaxError):
            return None
    # if the parsed value is not a list/tuple, return None
    if not isinstance(parsed, (list, tuple)):
        return None
    # try to cast every element to float
    try:
        return [float(x) for x in parsed]
    except (TypeError, ValueError):
        return None

# helper function to build a feature DataFrame with text + per-dim embedding columns
def build_feature_frame(df, text_col, embedding_col):
    # parse every cell in the embedding column
    parsed = df[embedding_col].apply(parse_embedding)
    # find the rows where parsing succeeded
    valid_mask = parsed.notna()
    # count how many rows failed to parse
    dropped_parse = (~valid_mask).sum()
    # report the number of dropped rows
    if dropped_parse:
        print(f"Dropped {dropped_parse} rows: unparseable '{embedding_col}'")
    # keep only the valid rows
    df = df.loc[valid_mask].copy()
    # keep the parsed embeddings aligned with the kept rows
    parsed = parsed.loc[valid_mask]

    # find the dominant embedding length and keep only rows matching it
    lengths = parsed.apply(len)
    # if no embeddings remain, raise an error
    if lengths.empty:
        raise ValueError(
            f"No valid embeddings found in column '{embedding_col}'. "
            f"Check the CSV format."
        )
    # find the most common embedding length
    dom_len = int(lengths.mode().iloc[0])
    # find the rows with a different length
    bad_len_mask = lengths != dom_len
    # if there are any rows with a different length, drop them
    if bad_len_mask.any():
        print(f"Dropped {bad_len_mask.sum()} rows: embedding length != {dom_len}")
        df = df.loc[~bad_len_mask].copy()
        parsed = parsed.loc[~bad_len_mask]

    # build the embedding matrix
    emb_matrix = np.asarray(parsed.tolist(), dtype=np.float32)
    # build the embedding column names
    emb_cols = [f"emb_{i:04d}" for i in range(dom_len)]
    # build the embedding DataFrame
    emb_df = pd.DataFrame(emb_matrix, columns=emb_cols, index=df.index)

    # concatenate the text column and the embedding columns
    out = pd.concat(
        [df[text_col].astype(str).rename(text_col), emb_df],
        axis=1,
    )
    # return the feature frame, the embedding column names, and the embedding dimension
    return out, emb_cols, dom_len
# // end of code modified by Claude 4.7 opus model //

# helper function to save the confusion matrix
def save_confusion_matrix(y_true, y_pred, classes, tag, out_dir):
    # calculate the confusion matrix
    cm = confusion_matrix(y_true, y_pred, labels=classes)
    # convert the confusion matrix to a pandas DataFrame
    cm_df = pd.DataFrame(cm, index=classes, columns=classes)
    # set the index name
    cm_df.index.name = "Skutečná třída"
    # set the columns name
    cm_df.columns.name = "Predikovaná třída"
    # save the confusion matrix to a CSV file
    cm_df.to_csv(out_dir / f"confusion_matrix_{tag}_param.csv")
    # create a figure and an axis

    # create a figure and an axis
    fig, ax = plt.subplots(figsize=(9, 7))
    # plot the confusion matrix
    ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes).plot(
        cmap=plt.cm.Blues, ax=ax, values_format="d"
    )
    # set the title
    ax.set_title(f"Confusion matrix")
    # save the figure
    plt.tight_layout()
    # save the figure
    plt.savefig(out_dir / f"confusion_matrix_{tag}_param.png", dpi=300, bbox_inches="tight")
    # close the figure
    plt.close(fig)

# helper function to save the train scores
def save_train_scores(model, X_train, y_train, X_val, y_val,
                      cv, n_jobs, random_state, tag, out_dir):
    # create a stratified k-fold object
    skf = StratifiedKFold(n_splits=cv, shuffle=True, random_state=random_state)

    # define the metrics
    metrics = ["accuracy", "f1_macro", "f1_weighted",
               "precision_weighted", "recall_weighted"]

    # create a list to store the scores
    rows = []
    # iterate over the metrics
    for m in metrics:
        # cross-validate the model
        scores = cross_val_score(model, X_train, y_train, cv=skf,
                                 scoring=m, n_jobs=n_jobs)
        # iterate over the scores
        for fold_idx, s in enumerate(scores):
            # add the score to the list
            rows.append({"metric": m, "fold": fold_idx, "score": s})
        # add the mean score to the list
        rows.append({"metric": m, "fold": "mean", "score": float(scores.mean())})
        # add the standard deviation score to the list
        rows.append({"metric": m, "fold": "std",  "score": float(scores.std())})

    # fit the model on the training data
    fitted = model.fit(X_train, y_train)
    # calculate the train accuracy
    train_acc = fitted.score(X_train, y_train)
    # calculate the validation accuracy
    val_acc = fitted.score(X_val, y_val)
    # add the train accuracy to the list
    rows.append({"metric": "train_accuracy_full", "fold": "-", "score": train_acc})
    # add the validation accuracy to the list
    rows.append({"metric": "val_accuracy_full",  "fold": "-", "score": val_acc})
    rows.append({"metric": "overfit_gap",         "fold": "-",
                 "score": train_acc - val_acc})

    # convert the list to a pandas DataFrame
    df = pd.DataFrame(rows)
    # save the DataFrame to a CSV file
    df.to_csv(out_dir / f"train_scores_{tag}_param.csv", index=False)
    # return the fitted model, the train accuracy, and the validation accuracy
    return fitted, train_acc, val_acc

# // this part of code was modified by Claude 4.7 opus model //
# helper function to extract feature names from a ColumnTransformer pipeline
def get_feature_names_from_ct(pipeline):
    # try to get the ColumnTransformer step named 'features'
    try:
        ct = pipeline.named_steps["features"]
    # if the ColumnTransformer is not found, return None
    except (KeyError, AttributeError):
        return None
    # create a list to store the feature names
    names = []
    # try to collect feature names from both branches
    try:
        # text branch: TfidfVectorizer inside a sub-pipeline called 'text'
        text_branch = dict(ct.named_transformers_).get("text")
        # if the text branch exists, get its tfidf step
        if text_branch is not None:
            # if the text branch is a pipeline, get the tfidf step from it
            if hasattr(text_branch, "named_steps"):
                tfidf = text_branch.named_steps.get("tfidf")
            # otherwise the branch itself is the tfidf
            else:
                tfidf = text_branch
            # if the tfidf is found, extend the names list with prefixed feature names
            if tfidf is not None and hasattr(tfidf, "get_feature_names_out"):
                names.extend(
                    [f"text::{n}" for n in tfidf.get_feature_names_out()]
                )
        # embedding branch: just the raw column names, prefixed
        emb_cols = getattr(ct, "transformers_", [])
        # iterate over the transformers
        for name, _trans, cols in emb_cols:
            # if the branch is the embedding branch, extend the names list
            if name == "emb" and cols is not None:
                names.extend([f"emb::{c}" for c in cols])
    # if anything goes wrong, warn and return None
    except Exception as e:
        print(f"[warn] could not collect feature names: {e}")
        return None
    # return the names array, or None if empty
    return np.asarray(names) if names else None
#// end of code modified by Claude 4.7 opus model //

# helper function to save the feature importance
def save_feature_importance(pipeline, out_dir, top_k=25):
    # get the feature names from the ColumnTransformer
    feat_names = get_feature_names_from_ct(pipeline)
    # try to get the classifier
    try:
        clf = pipeline.named_steps["clf"]
    # if the classifier is not found, return
    except (KeyError, AttributeError):
        return
    # if the feature names or classifier coefficients are missing, return
    if feat_names is None or not hasattr(clf, "coef_"):
        return

    # get the coefficients
    coef = clf.coef_
    # get the classes
    classes = clf.classes_
    # if the feature-name and coef shapes do not match, warn and return
    if coef.shape[1] != len(feat_names):
        print(f"[warn] feature-name/coef shape mismatch: "
              f"{len(feat_names)} vs {coef.shape[1]} -- skipping importance")
        return

    # class list for the output DataFrame
    class_list = classes

    # create a list to store the feature importance
    rows = []
    # iterate over the classes
    for i, cls in enumerate(class_list):
        # if the coefficients are for a binary classification, set the row index to 0
        row_idx = 0 if coef.shape[0] == 1 else i
        # get the coefficients for the current class
        c = coef[row_idx]
        # get the top k features
        top_pos = np.argsort(c)[-top_k:][::-1]
        # iterate over the top k features
        for rank, idx in enumerate(top_pos):
            # add the feature importance to the list
            rows.append({
                "class": cls, "rank": rank + 1,
                "feature": feat_names[idx], "coef": float(c[idx]),
            })
    # convert the list to a pandas DataFrame
    pd.DataFrame(rows).to_csv(out_dir / "feature_importance_best.csv", index=False)

# helper function to build the pipeline
def make_pipeline(text_col, emb_cols, *, tfidf_kwargs=None, clf_kwargs=None):
    # default to empty kwargs if none are provided
    tfidf_kwargs = tfidf_kwargs or {}
    clf_kwargs = clf_kwargs or {}

    # text branch: TfidfVectorizer
    text_branch = Pipeline([
        ("tfidf", TfidfVectorizer(**tfidf_kwargs)),
    ])
    # embedding branch: StandardScaler keeps embedding scale comparable to L2-normalised TF-IDF
    emb_branch = Pipeline([
        ("scaler", StandardScaler(with_mean=True)),
    ])

    # combine the two branches in a ColumnTransformer
    features = ColumnTransformer(
        transformers=[
            ("text", text_branch, text_col),
            ("emb",  emb_branch,  emb_cols),
        ],
        sparse_threshold=0.3,
    )

    # final pipeline: ColumnTransformer -> LogisticRegression
    return Pipeline([
        ("features", features),
        ("clf", LogisticRegression(**clf_kwargs)),
    ])

# --- 1. Main function ---
# initialize the arguments
args = Args(CONFIG)
# create the output directory
out_dir = Path(args.out)
# create the output directory
out_dir.mkdir(parents=True, exist_ok=True)
# set the stdout to the log file
sys.stdout = Tee(out_dir / "run_log.txt")
# set the start time
t0 = time.time()

# print the header
print("=" * 70)
# print the header
print("Text + image-embedding classification training")
print("=" * 70)
print(f"args: {vars(args)}")

# load the data
df = pd.read_csv(args.data)
# print the number of rows and the columns
print(f"\nLoaded {len(df)} rows from {args.data}")
# print the columns
print(f"Columns: {list(df.columns)}")

# check that all required columns are present
required = {args.text_col, args.label_col, args.embedding_col}
# get the missing columns
missing = required - set(df.columns)
# if any required columns are missing, raise an error
if missing:
    raise ValueError(
        f"CSV is missing required columns: {sorted(missing)}. "
        f"Found: {list(df.columns)}"
    )

# drop rows missing label, text, or embedding
before = len(df)
# drop rows missing label, text, or embedding
df = df.dropna(subset=[args.label_col, args.text_col, args.embedding_col])
# drop rows with empty text
df = df[df[args.text_col].astype(str).str.strip() != ""]
# print the number of rows dropped
print(f"Dropped {before - len(df)} rows with missing/empty text/label/embedding")

# parse the embedding column into per-dimension feature columns
feat_df, emb_cols, emb_dim = build_feature_frame(
    df, text_col=args.text_col, embedding_col=args.embedding_col,
)

# align the labels with the feature frame
y = df.loc[feat_df.index, args.label_col]
# print the embedding dimension
print(f"Embedding dimension: {emb_dim}")
# print the number of usable rows after parsing
print(f"Usable rows after parsing: {len(feat_df)}")

# print the class distribution
print("\nClass distribution:")
# print the class distribution
print(y.value_counts().sort_index())

# the feature DataFrame holds both the text column and all embedding columns
X = feat_df

# split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=args.val_size,
    stratify=y,
    random_state=args.random_state,
)
# print the number of rows in the training and validation sets
print(f"\nSplit: train={len(X_train)}, val={len(X_val)}")
# get the unique classes
classes_sorted = sorted(y.unique())

# --- 2. Training with START parameters (baseline) ---
# print the header
print("\n" + "=" * 70)
print("1) Training with START parameters (baseline)")
print("=" * 70)

# create the start pipeline
start_pipeline = make_pipeline(
    text_col=args.text_col,
    emb_cols=emb_cols,
    tfidf_kwargs=dict(
        max_features=20000,
        ngram_range=(1, 2),
    ),
    clf_kwargs=dict(
        max_iter=5000,
        class_weight="balanced",
        random_state=args.random_state,
    ),
)

# start the timer
t_start = time.time()
# fit the start pipeline
fitted_start, tr_acc_s, val_acc_s = save_train_scores(
    start_pipeline, X_train, y_train, X_val, y_val,
    cv=args.cv, n_jobs=args.n_jobs, random_state=args.random_state,
    tag="start", out_dir=out_dir,
)
# print the time taken to fit the start pipeline
print(f"Start baseline fit in {time.time() - t_start:.1f}s")
print(f"  Train accuracy: {tr_acc_s:.4f}")
print(f"  Val   accuracy: {val_acc_s:.4f}")

# predict the start pipeline
y_pred_start = fitted_start.predict(X_val)
# create the classification report
report_start = classification_report(y_val, y_pred_start, digits=4)
# save the classification report
(out_dir / "classification_report_start_param.txt").write_text(
    report_start, encoding="utf-8"
)
print("\nClassification report (start):\n" + report_start)

# save confusion matrix
save_confusion_matrix(y_val, y_pred_start, classes_sorted,
                      tag="start", out_dir=out_dir)
# save the start pipeline
joblib.dump(fitted_start, out_dir / "model_start.pkl")

# --- 3. Hyperparameter search for BEST parameters ---
# print the header
print("\n" + "=" * 70)
print("2) Hyperparameter search for BEST parameters")
print("=" * 70)

# create the search pipeline
search_pipeline = make_pipeline(
    text_col=args.text_col,
    emb_cols=emb_cols,
    clf_kwargs=dict(random_state=args.random_state),
)

# create the parameter distribution
param_dist = {
    "features__text__tfidf__max_features": randint(2000, 80000),
    "features__text__tfidf__ngram_range": [(1, 1), (1, 2), (1, 3), (1, 4)],
    "features__text__tfidf__min_df": randint(1, 25),
    "features__text__tfidf__max_df": [0.85, 0.9, 0.95, 1.0],
    "features__text__tfidf__sublinear_tf": [True, False],
    "features__text__tfidf__analyzer": ["word", "char_wb"],
    "clf__C": loguniform(0.01, 50),
    "clf__max_iter": randint(3000, 15000),
    "clf__class_weight": [None, "balanced"],
    "clf__solver": ["saga", "lbfgs"],
}

# create the stratified k-fold object
skf = StratifiedKFold(n_splits=args.cv, shuffle=True,
                      random_state=args.random_state)

# create the scoring dictionary
scoring = {
    "f1_macro":            "f1_macro",
    "f1_weighted":         "f1_weighted",
    "precision_weighted":  "precision_weighted",
    "recall_weighted":     "recall_weighted",
    "balanced_accuracy":   "balanced_accuracy",
}

# create the randomized search object
random_search = RandomizedSearchCV(
    search_pipeline,
    param_distributions=param_dist,
    n_iter=args.n_iter,
    cv=skf,
    scoring=scoring,
    refit="f1_macro",
    n_jobs=args.n_jobs,
    verbose=2,
    random_state=args.random_state,
    error_score=0.0,
    return_train_score=False,
)

# start the timer
t_search = time.time()
# fit the randomized search object (with partial-result rescue on interrupt)
try:
    random_search.fit(X_train, y_train)
except (KeyboardInterrupt, SystemExit):
    # if PBS sends SIGTERM near walltime, try to persist what we have
    print("\n[warn] Search interrupted -- attempting to save partial results")
    if hasattr(random_search, "cv_results_"):
        pd.DataFrame(random_search.cv_results_).to_csv(
            out_dir / "cv_search_results_partial.csv", index=False
        )
    raise
# print the time taken to fit the randomized search object
print(f"\nSearch finished in {(time.time() - t_search)/60:.1f} min")
# print the best f1_macro score
print(f"Best CV f1_macro: {random_search.best_score_:.4f}")
# print the best parameters
print(f"Best params: {random_search.best_params_}")

# save the best parameters
with open(out_dir / "best_params.json", "w", encoding="utf-8") as f:
    json.dump(
        {k: (list(v) if isinstance(v, tuple) else v)
         for k, v in random_search.best_params_.items()},
        f, indent=2, default=str,
    )
# save the cv search results
pd.DataFrame(random_search.cv_results_).to_csv(
    out_dir / "cv_search_results.csv", index=False
)
# get the best model
best_model = random_search.best_estimator_

# fit the best model
fitted_best, tr_acc_b, val_acc_b = save_train_scores(
    best_model, X_train, y_train, X_val, y_val,
    cv=args.cv, n_jobs=args.n_jobs, random_state=args.random_state,
    tag="best", out_dir=out_dir,
)
# print the train and validation accuracy
print(f"\nBest model - train acc: {tr_acc_b:.4f}, val acc: {val_acc_b:.4f}")

# predict the best model
y_pred_best = fitted_best.predict(X_val)
# create the classification report
report_best = classification_report(y_val, y_pred_best, digits=4)
# save the classification report
(out_dir / "classification_report_best_param.txt").write_text(
    report_best, encoding="utf-8"
)
print("\nClassification report (best):\n" + report_best)

# save confusion matrix
save_confusion_matrix(y_val, y_pred_best, classes_sorted,
                      tag="best", out_dir=out_dir)
# save the feature importance
save_feature_importance(fitted_best, out_dir)
# save the best model (along with metadata needed for inference)
joblib.dump(
    {"model": fitted_best, "classes": list(fitted_best.classes_),
     "best_params": random_search.best_params_,
     "embedding_dim": emb_dim,
     "embedding_cols": emb_cols,
     "text_col": args.text_col},
    out_dir / "model_best.pkl",
)

# --- 4. Summary ---
# create the summary dictionary
summary = {
    # print the number of rows
    "n_rows": int(len(feat_df)),
    # print the number of rows in the training set
    "n_train": int(len(X_train)),
    # print the number of rows in the validation set
    "n_val": int(len(X_val)),
    # print the embedding dimension
    "embedding_dim": emb_dim,
    # print the classes
    "classes": [str(c) for c in classes_sorted],
    # print the train and validation accuracy
    "start": {"train_acc": tr_acc_s, "val_acc": val_acc_s},
    # print the best f1_macro score
    "best":  {"train_acc": tr_acc_b, "val_acc": val_acc_b,
              "cv_f1_macro": float(random_search.best_score_)},
    # print the total runtime in minutes
    "total_runtime_min": (time.time() - t0) / 60,
}

# save the summary
with open(out_dir / "summary.json", "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2)

# print the total runtime in minutes
print("\n" + "=" * 70)
print(f"All done in {(time.time() - t0)/60:.1f} min")
print(f"Results saved to: {out_dir.resolve()}")
print("=" * 70)