// Implementation of PdfViewerWindow.

#include "pdfviewerwindow.h"
#include "ui_pdfviewerwindow.h"

#include <QPdfPageNavigator>
#include <QCloseEvent>
#include <QGestureEvent>
#include <QPinchGesture>
#include <QScrollBar>
#include <QCursor>
#include <memory>

// Protected constructor for subclasses that supply their own .ui file.
PdfViewerWindow::PdfViewerWindow(QWidget* parent)
    : QWidget(parent)
    , m_doc(new QPdfDocument(this))
{}

// Public constructor — instantiates the base .ui and loads pdfPath.
PdfViewerWindow::PdfViewerWindow(const QString& pdfPath, QWidget* parent, QPdfView::PageMode pageMode)
    : QWidget(parent)
    , m_doc(new QPdfDocument(this))
{
    // Instantiate the base .ui and prepare the view geometry.
    m_baseUi = new Ui::PdfViewerWindow;
    m_baseUi->setupUi(this);

    m_pdfView        = m_baseUi->pdfView;
    m_zoomInBtn      = m_baseUi->zoomInBtn;
    m_zoomOutBtn     = m_baseUi->zoomOutBtn;
    m_prevBtn        = m_baseUi->prevBtn;
    m_nextBtn        = m_baseUi->nextBtn;
    m_pageSpin       = m_baseUi->pageSpin;
    m_pageCountLabel = m_baseUi->pageCountLabel;

    initViewer(pdfPath, pageMode);
}

// Block document/navigator signals before deleting the UI to prevent dangling callbacks.
PdfViewerWindow::~PdfViewerWindow()
{
    if (m_doc) m_doc->blockSignals(true);
    if (m_nav) m_nav->blockSignals(true);

    delete m_baseUi;
}

// Wire up the PDF view: event filters, signals, gestures, and initial document load.
void PdfViewerWindow::initViewer(const QString& pdfPath, QPdfView::PageMode pageMode)
{
    m_pdfView->installEventFilter(this);
    m_pdfView->viewport()->installEventFilter(this);
    m_zoomTimer.start();
    m_scrollTimer.start();

    m_pdfView->setDocument(m_doc);
    m_pdfView->setPageMode(pageMode);
    m_nav = m_pdfView->pageNavigator();

    // Enable touch pinch-to-zoom at the OS level
    m_pdfView->grabGesture(Qt::PinchGesture);

    connect(m_zoomInBtn,  &QPushButton::clicked, this, &PdfViewerWindow::zoomIn);
    connect(m_zoomOutBtn, &QPushButton::clicked, this, &PdfViewerWindow::zoomOut);
    connect(m_prevBtn,    &QPushButton::clicked, this, &PdfViewerWindow::prevPage);
    connect(m_nextBtn,    &QPushButton::clicked, this, &PdfViewerWindow::nextPage);

    connect(m_pageSpin, &QSpinBox::valueChanged,
            this, &PdfViewerWindow::pageSpinChanged);
    connect(m_doc, &QPdfDocument::pageCountChanged,
            this,  &PdfViewerWindow::onPageCountChanged);
    connect(m_nav, &QPdfPageNavigator::currentPageChanged,
            this,  &PdfViewerWindow::onCurrentPageChanged);

    m_doc->load(pdfPath);
}

// Apply a relative zoom factor while keeping the cursor anchor in place.
// This code was generate by Claude Opus 4.7 //
void PdfViewerWindow::applyZoom(double factor)
{
    // Guard: ignore invalid factors
    if (factor <= 0 || qIsNaN(factor) || qIsInf(factor))
        return;

    // Get the current zoom factor.
    double current = m_pdfView->zoomFactor();

    // Calculate the new zoom factor, clamped to the defined boundaries.
    double newZoom = qBound(MIN_ZOOM, current * factor, MAX_ZOOM);

    // Guard: ignore micro-changes to save render cycles
    if (qAbs(newZoom - current) < 0.001)
        return;

    // Calculate the ratio to adjust scrollbars correctly
    double ratio = newZoom / current;

    QScrollBar *hBar = m_pdfView->horizontalScrollBar();
    QScrollBar *vBar = m_pdfView->verticalScrollBar();

    // Determine zoom anchor point
    QPoint globalCursorPos = QCursor::pos();
    QPoint viewportPos = m_pdfView->viewport()->mapFromGlobal(globalCursorPos);
    QPointF center;

    // If the mouse cursor is over the PDF, zoom toward the cursor. 
    if (m_pdfView->viewport()->rect().contains(viewportPos)) {
        center = viewportPos;
    } else {
        center = QPointF(m_pdfView->viewport()->width() / 2.0,
                         m_pdfView->viewport()->height() / 2.0);
    }

    // Capture absolute spatial position before zooming
    double oldX = hBar->value() + center.x();
    double oldY = vBar->value() + center.y();

    // Apply the zoom
    m_pdfView->setZoomFactor(newZoom);

    // Shift scrollbars to keep the calculated anchor point under the cursor/center
    hBar->setValue(qRound(oldX * ratio - center.x()));
    vBar->setValue(qRound(oldY * ratio - center.y()));
}
// End of code generated by Claude Opus 4.7 //

// Zoom in by 20%.
void PdfViewerWindow::zoomIn()  { applyZoom(1.2); }

// Zoom out by ~9% (1 / 1.1).
void PdfViewerWindow::zoomOut() { applyZoom(1.0 / 1.1); }

// Navigate to the previous page.
void PdfViewerWindow::prevPage() { jumpToPage0(m_nav->currentPage() - 1); }

// Navigate to the next page.
void PdfViewerWindow::nextPage() { jumpToPage0(m_nav->currentPage() + 1); }

// Spin-box slot — convert from 1-based to 0-based and execute jump.
void PdfViewerWindow::pageSpinChanged(int page1based)
{
    jumpToPage0(page1based - 1);
}

// Slot reacting to QPdfDocument::pageCountChanged.
void PdfViewerWindow::onPageCountChanged(int pageCount)
{
    m_pageCountLabel->setText(QString("/ %1").arg(pageCount));
    m_pageSpin->setMaximum(qMax(1, pageCount));

    // Update UI constraints based on the new total
    updateUiEnabled();
}

// Update the page spin-box without re-emitting valueChanged to avoid cyclical calls.
void PdfViewerWindow::onCurrentPageChanged(int page0based)
{
    m_pageSpin->blockSignals(true);
    m_pageSpin->setValue(page0based + 1);
    m_pageSpin->blockSignals(false);
    updateUiEnabled();
}

// Jump to a 0-based page index after verifying bounds.
void PdfViewerWindow::jumpToPage0(int page0based)
{
    if (page0based >= 0 && page0based < m_doc->pageCount()) {
        const bool isSinglePage = (m_pdfView->pageMode() == QPdfView::PageMode::SinglePage);
        
        // Ensure viewport resets to standard view when navigating in single-page mode
        if (isSinglePage && m_pdfView->zoomFactor() > 1.0 + 0.001)
            m_pdfView->setZoomFactor(1.0);
            
        m_nav->jump(page0based, QPoint(), m_nav->currentZoom());
    }
}

// Refresh enabled state of the navigation controls.
void PdfViewerWindow::updateUiEnabled()
{
    int current = m_nav->currentPage();
    int count   = m_doc->pageCount();
    
    m_prevBtn->setEnabled(current > 0);
    m_nextBtn->setEnabled(current < count - 1);
    m_pageSpin->setEnabled(count > 0);
}

// Double-click zoom: left = +10%, right = -10%, middle = reset to 1.0.
void PdfViewerWindow::mouseDoubleClickEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton)
        applyZoom(1.1);
    else if (event->button() == Qt::RightButton)
        applyZoom(1.0 / 1.1);
    else if (event->button() == Qt::MiddleButton)
        m_pdfView->setZoomFactor(1.0);
    else
        QWidget::mouseDoubleClickEvent(event);

    event->accept();
}

// Wheel handler — intercepts scrolling events to allow for Control-based zooming.
void PdfViewerWindow::wheelEvent(QWheelEvent *event)
{
    // Guard: ignore empty/invalid events
    if (event->angleDelta().isNull() && event->pixelDelta().isNull()) {
        event->accept();
        return;
    }

    // Ctrl+Wheel Zooming Logic
    if (event->modifiers() & Qt::ControlModifier)
    {
        // Throttle input to ensure stable zooming
        if (m_zoomTimer.elapsed() < ZOOM_THROTTLE_MS) {
            event->accept();
            return;
        }
        m_zoomTimer.restart();

        // Prefer pixelDelta for smoother touchpad interaction if available
        int delta = !event->pixelDelta().isNull()
                        ? event->pixelDelta().y()
                        : event->angleDelta().y();

        if (delta > 0)
            applyZoom(1.05);
        else if (delta < 0)
            applyZoom(1.0 / 1.05);

        event->accept();
        return;
    }

    // Standard Scrolling Logic (Throttled)
    // This code was generate by Claude Opus 4.7 //
    if (m_scrollTimer.elapsed() < SCROLL_THROTTLE_MS) {
        event->accept();
        return;
    }
    // End of code generated by Claude Opus 4.7 //
    m_scrollTimer.restart();

    QWidget::wheelEvent(event);
}

// General gesture handler — catches pinch-to-zoom.
// This code was modified by Claude Opus 4.7 //
bool PdfViewerWindow::event(QEvent *event)
{
    if (event->type() == QEvent::Gesture)
    {
        QGestureEvent *gestureEvent = static_cast<QGestureEvent*>(event);
        
        if (QPinchGesture *pinch = static_cast<QPinchGesture*>(gestureEvent->gesture(Qt::PinchGesture)))
        {
            // Throttle pinch zooming to avoid overwhelming the PDF renderer
            if (m_zoomTimer.elapsed() >= ZOOM_THROTTLE_MS)
            {
                double scale = pinch->scaleFactor();
                if (scale != 1.0)
                    applyZoom(scale);
                
                m_zoomTimer.restart();
            }
            return true;
        }
    }
    return QWidget::event(event);
}
// End of code modified by Claude Opus 4.7 //

// Keyboard shortcuts for view control.
void PdfViewerWindow::keyPressEvent(QKeyEvent *event)
{
    switch (event->key())
    {
    case Qt::Key_Plus:
        applyZoom(1.2);
        break;
    case Qt::Key_Minus:
        applyZoom(1.0 / 1.2);
        break;
    case Qt::Key_0:
        m_pdfView->setZoomFactor(1.0);
        break;
    case Qt::Key_Escape:
        close();
        break;
    default:
        QWidget::keyPressEvent(event);
        break;
    }
}

// Determine whether horizontal arrow keys should jump to an adjacent page.
bool PdfViewerWindow::shouldAllowArrowPageTurn() const
{
    const bool isMultiPage = (m_pdfView->pageMode() == QPdfView::PageMode::MultiPage);

    // In multi-page mode: only turn page if zoomed out (≤110%) to avoid conflicts
    if (isMultiPage) {
        return m_pdfView->zoomFactor() <= 1.10;
    } else {
        // In single-page mode: allow page turn only when ≥90% of the page height is visible.
        int page = m_nav->currentPage();
        if (page < 0 || page >= m_doc->pageCount())
            return true;

        QSizeF pageSize = m_doc->pagePointSize(page);
        if (pageSize.height() <= 0)
            return true;

        double zoom         = m_pdfView->zoomFactor();
        double pageHeightPx = pageSize.height() * zoom;
        double viewportH    = static_cast<double>(m_pdfView->viewport()->height());

        return (viewportH / pageHeightPx) >= 0.9;
    }
}

// Event filter applied to QPdfView to enforce custom controls directly on the canvas.
bool PdfViewerWindow::eventFilter(QObject *watched, QEvent *event)
{
    // Filter strictly applies to the viewer and its internal viewport.
    const bool isPdfView  = (watched == m_pdfView);
    const bool isViewport = (watched == m_pdfView->viewport());
    if (!isPdfView && !isViewport)
        return QWidget::eventFilter(watched, event);

    // Intercept Mouse Wheel for Ctrl+Zoom overrides (bypassing default scrolling).
    if (event->type() == QEvent::Wheel)
    {
        QWheelEvent *we = static_cast<QWheelEvent*>(event);
        if (we->modifiers() & Qt::ControlModifier)
        {
            wheelEvent(we);
            return true;
        }
    }

    // Intercept key presses to ensure global keyboard scrolling and page turning
    if (event->type() == QEvent::KeyPress)
    {
        QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
        int scrollStep = 50;

        switch (keyEvent->key())
        {
        case Qt::Key_Up:
            m_pdfView->verticalScrollBar()->setValue(
                m_pdfView->verticalScrollBar()->value() - scrollStep);
            return true;

        case Qt::Key_Down:
            m_pdfView->verticalScrollBar()->setValue(
                m_pdfView->verticalScrollBar()->value() + scrollStep);
            return true;

        // Shift+Space = previous page. Space = next page.
        case Qt::Key_Space:
            if (keyEvent->modifiers() & Qt::ShiftModifier)
                prevPage();
            else
                nextPage();
            return true;

        case Qt::Key_Right:
            if (m_pdfView->zoomFactor() > 1.0 + 0.001) {
                m_pdfView->horizontalScrollBar()->setValue(
                    m_pdfView->horizontalScrollBar()->value() + scrollStep);
            } else if (shouldAllowArrowPageTurn()) {
                nextPage();
            }
            return true;

        case Qt::Key_Left:
            if (m_pdfView->zoomFactor() > 1.0 + 0.001) {
                m_pdfView->horizontalScrollBar()->setValue(
                    m_pdfView->horizontalScrollBar()->value() - scrollStep);
            } else if (shouldAllowArrowPageTurn()) {
                prevPage();
            }
            return true;

        default:
            break;
        }
    }

    // Mouse Press: Initiate click-and-drag panning
    if (event->type() == QEvent::MouseButtonPress)
    {
        QMouseEvent *me = static_cast<QMouseEvent*>(event);

        if (me->button() == Qt::LeftButton)
        {
            m_isPanning = true;
            m_panStart  = me->globalPosition();
            m_pdfView->viewport()->setCursor(Qt::ClosedHandCursor);
            return true;
        }
    }

    // Mouse Move: Execute panning movement calculations and apply scroll
    // This code was modified by Claude Opus 4.7 //
    if (event->type() == QEvent::MouseMove && m_isPanning)
    {
        QMouseEvent *me = static_cast<QMouseEvent*>(event);

        QPointF delta = me->globalPosition() - m_panStart;
        m_panStart = me->globalPosition();

        auto *hBar = m_pdfView->horizontalScrollBar();
        auto *vBar = m_pdfView->verticalScrollBar();

        hBar->setValue(hBar->value() - delta.x());
        vBar->setValue(vBar->value() - delta.y());

        return true;
    }

    // Mouse Release: Terminate panning state
    if (event->type() == QEvent::MouseButtonRelease)
    {
        QMouseEvent *me = static_cast<QMouseEvent*>(event);

        if (me->button() == Qt::LeftButton && m_isPanning)
        {
            m_isPanning = false;
            m_pdfView->viewport()->setCursor(Qt::ArrowCursor);
            return true;
        }
    }
    // End of code modified by Claude Opus 4.7 //

    return QWidget::eventFilter(watched, event);
}